name: Build and Push ArgoCD KSOPS Image

on:
  push:
    branches:
      - main  # o cambia a la rama que uses

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Harbor registry
        uses: docker/login-action@v3
        with:
          registry: harbor.migbertweb.site
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: harbor.migbertweb.site/prod-registry/argocd-ksops:latest
